import type { CategoryId, FingerId, HandJewelryType } from "@/types";
import { preservationFooter, productLockFooter } from "./preservationBlocks";

/**
 * OpenAI GPT Image prompt builder.
 *
 *  Distinct from `lib/providers/prompts.ts` (which targets fal.ai's FLUX
 *  models) because:
 *    - GPT Image accepts multiple reference images via `image[]`.
 *    - Mask convention is opposite (transparent = editable). The wording
 *      reflects this.
 *    - Hand-jewelry has subtype-specific wording (ring vs bracelet) and
 *      can address a target finger.
 *
 *  Each prompt is composed of:
 *    1. A short "what to do" lead specific to the category.
 *    2. The shared preservation footer (customer + product + no-hallucination
 *       + mask blocks). See `preservationBlocks.ts`.
 */

export interface OpenAITryOnPromptOptions {
  category: CategoryId;
  productSubtype?: HandJewelryType;
  maskUsed: boolean;
  targetFinger?: FingerId;
  notes?: string;
  /**
   * True when the product has been pre-composited onto the base image and
   * will be re-stamped on top after the AI returns (product-lock
   * pipeline). The prompt switches to "integrate only — do not redraw".
   */
  productLocked?: boolean;
  /**
   * True when both `compositeImage` and `maskImage` were generated by
   * the app (no user-supplied mask). Triggers the strict
   * `AUTO_MASKED_ACCESSORY_PROMPT` instead of the per-category
   * placement lead.
   */
  autoMaskedAccessory?: boolean;
}

const FINGER_LABEL: Record<FingerId, string> = {
  index: "index finger",
  middle: "middle finger",
  ring: "ring finger",
  pinky: "pinky finger",
};

// ──────────────────────────────────────────────────────────────────────────
//  Category-specific leads — product-LOCK variants
//  ("the product has already been positioned, only integrate").
// ──────────────────────────────────────────────────────────────────────────

/**
 * Generic accessory lock lead. Exported so non-default callers (e.g.
 * future operator overrides) can reach for the generic wording without
 * picking a specific category.
 */
export const ACCESSORY_LOCK_GENERIC =
  "Use the customer image as the base. The product has already been " +
  "positioned as a locked reference layer. Edit only the masked area " +
  "to improve realistic contact shadows, edge blending, local " +
  "lighting, and surface integration. Do not redesign, move, replace, " +
  "recolor, or redraw the product. Do not change the customer, hand, " +
  "fingers, face, skin, body, background, pose, or lighting outside " +
  "the mask. Everything outside the mask must remain unchanged.";

function watchLockLead(): string {
  return (
    "The watch is already positioned on the wrist as a locked product " +
    "reference. Improve only the local contact shadows, wrist " +
    "integration, edge blending, and realistic lighting around the " +
    "watch. Do not move the watch. Do not redraw the watch. Do not " +
    "change the dial, bracelet, metal, size, color, or details. Do " +
    "not alter the hand, fingers, skin texture, arm hair, background, " +
    "or anatomy."
  );
}

function glassesLockLead(): string {
  return (
    "The glasses are already positioned as a locked product reference. " +
    "Improve only local shadows, reflections, and blending around the " +
    "frame, nose bridge, and temples. Do not redesign the frame. Do " +
    "not change the eyes, face, skin, mouth, hair, identity, or " +
    "background."
  );
}

function ringLockLead(opts: OpenAITryOnPromptOptions): string {
  const finger = opts.targetFinger
    ? FINGER_LABEL[opts.targetFinger]
    : "the selected finger";
  return (
    `The ring is already positioned on ${finger} as a locked product ` +
    "reference. Improve only contact shadows, reflections, and " +
    "blending around the ring. Do not change the ring design, stones, " +
    "metal, shape, or color. Do not alter fingers, nails, hand " +
    "anatomy, skin, or background."
  );
}

function braceletLockLead(): string {
  return (
    "The bracelet is already positioned around the wrist as a locked " +
    "product reference. Improve only contact shadows, reflections, " +
    "and blending around the bracelet. Do not change the bracelet " +
    "design, stones, metal, shape, or color. Do not alter the wrist, " +
    "fingers, hand anatomy, skin, or background."
  );
}

function genericHandJewelryLockLead(): string {
  return (
    "The jewelry is already positioned as a locked product reference. " +
    "Improve only contact shadows, reflections, and blending around " +
    "the jewelry. Do not change the ring or bracelet design, stones, " +
    "metal, shape, or color. Do not alter fingers, nails, hand " +
    "anatomy, skin, or background."
  );
}

function headwearLockLead(): string {
  return (
    "The headwear is already positioned as a locked product reference. " +
    "Improve only edge blending, shadows, and lighting around the " +
    "headwear. Do not redesign the product. Do not change the face, " +
    "hair, identity, or background."
  );
}

// ──────────────────────────────────────────────────────────────────────────
//  Category-specific leads — placement variants
//  (used when the product was NOT pre-composited; the AI must still
//  place it on the body).
// ──────────────────────────────────────────────────────────────────────────

function watchLead(): string {
  return (
    "Use the customer wrist photo as the base image. Use the transparent " +
    "watch product image as the exact product reference. Add the watch " +
    "naturally around the visible wrist with realistic scale, perspective, " +
    "wrist curvature, and natural contact shadows. The strap must wrap " +
    "around the wrist instead of appearing as a flat sticker. The watch " +
    "face must remain sharp and recognizable; preserve the dial layout, " +
    "hour markers, sub-dials, hands, logo, bracelet links, and metal " +
    "finish exactly as in the product reference."
  );
}

function glassesLead(): string {
  return (
    "Use the customer face photo as the base image. Use the glasses " +
    "product image as the exact product reference. Place the frame " +
    "naturally on the face, aligned with the eyes, nose bridge, and " +
    "temples, with realistic scale, perspective, and shadows. Preserve " +
    "the exact frame shape, color, lens tint, bridge, and temples from " +
    "the product reference."
  );
}

function headwearLead(): string {
  return (
    "Use the customer portrait photo as the base image. Use the headwear " +
    "product image as the exact product reference. Place the cap, hat, or " +
    "beanie naturally on the head with realistic scale, perspective, and " +
    "shadows. It must sit naturally on the head and align with the " +
    "forehead and hairline. Preserve the exact product shape, color, " +
    "fabric, logo, and brim shape from the reference."
  );
}

function ringLead(opts: OpenAITryOnPromptOptions): string {
  const finger = opts.targetFinger
    ? FINGER_LABEL[opts.targetFinger]
    : "the selected finger";
  return (
    "Use the customer hand photo as the base image. Use the ring product " +
    "image as the exact product reference. Place the ring on " +
    finger +
    " only. The ring must wrap around the finger with realistic scale, " +
    "perspective, contact shadows, and metal reflections. Preserve the " +
    "exact ring shape, metal finish, gemstones, settings, and engravings " +
    "from the reference."
  );
}

function braceletLead(): string {
  return (
    "Use the customer hand or wrist photo as the base image. Use the " +
    "bracelet product image as the exact product reference. Place the " +
    "bracelet around the wrist with realistic scale, perspective, " +
    "curvature, and contact shadows. The bracelet should follow the " +
    "cylindrical shape of the wrist. Preserve the exact bracelet shape, " +
    "links, metal finish, gemstones, and pattern from the reference."
  );
}

function genericHandJewelryLead(): string {
  return (
    "Use the customer hand photo as the base image. Use the jewelry " +
    "product image as the exact product reference. Place the jewelry " +
    "naturally on the appropriate hand, finger, or wrist area with " +
    "realistic scale, perspective, and shadows. Preserve the exact " +
    "jewelry shape, material, color, gemstones, and pattern."
  );
}

function clothesLead(): string {
  return (
    "Use the customer body photo as the base image. Use the clothing " +
    "product image as the exact product reference. Dress the person in " +
    "the garment with realistic fit, folds, fabric texture, and " +
    "perspective. Preserve the exact garment color, pattern, logos, " +
    "fabric texture, and cut from the reference. Preserve the face, " +
    "hair, hands, and identity exactly. Avoid altering anything " +
    "outside the garment area."
  );
}

// ──────────────────────────────────────────────────────────────────────────
//  Auto-masked accessory prompt
//
//  Used when the app produced both `compositeImage` (user photo + product
//  placed at the right position by the deterministic pipeline) and
//  `maskImage` (feathered contact band around the product). This is the
//  default path for every accessory category, so the model can never
//  redesign the product or alter the customer.
// ──────────────────────────────────────────────────────────────────────────

export const AUTO_MASKED_ACCESSORY_PROMPT = `You are performing a realistic e-commerce virtual try-on edit.

The first image is the primary source of truth. It already contains the customer photo with the product placed in the intended position.
The product reference image shows the exact product that must be preserved.

Your task is not to redesign, replace, duplicate, recolor, simplify, or invent the product.
Your task is only to make the already placed product look naturally worn by the customer.

Edit only the masked area. Improve realistic contact, shadows, occlusion, reflections, scale consistency, perspective blending, and material integration.

Strict preservation rules:
- Preserve the customer's body, hand, face, skin texture, nails, hair, clothing and background outside the masked area.
- Do not change anatomy.
- Do not change finger length, hand shape, wrist shape, face shape or body proportions.
- Do not beautify, smooth, regenerate, repaint or reinterpret the customer.
- Preserve the exact product identity from the reference image.
- Do not replace the product with a different item.
- Do not duplicate the product.
- Do not create a second product.
- Do not show the product more than once anywhere in the image.
- Do not change the product color, material, shape, logo, dial layout, pattern, texture, decorations, bracelet links, frame shape or visible details.
- Do not invent new product elements.
- Do not simplify the product.
- Do not turn a black product into a silver product.
- Do not turn a colorful product into a plain product.
- The final image must look like the original customer photo with the exact supplied product naturally worn.

For watches:
- Preserve the exact watch case shape, bezel, dial, subdials, hands, markings, logo placement, date window, bracelet links, color accents and material.
- The watch is already positioned on the wrist.
- Only blend the watch with the wrist using realistic shadows, contact, perspective and slight skin occlusion.
- Do not create a different watch.
- Do not draw a second watch on the other wrist or anywhere else.

For glasses:
- Preserve the exact frame shape, color, lens style, bridge, temples and material.
- Preserve the customer's eyes, nose, face shape, skin texture and expression.
- Only blend nose pads, temples, reflections and shadows.

For rings and bracelets:
- Preserve exact product shape, stones, metal color, engraving, pattern and thickness.
- Preserve fingers, nails and skin.
- Do not change finger anatomy.

For headwear:
- Preserve the exact hat/cap shape, color, logo, texture and brim.
- Preserve face identity and hair except small natural occlusion in the masked contact area.

Important — the mask is only a technical editing guide. It must not appear in the final image:
- No white outlines around fingers, hands, face, or any object.
- No black outlines or segmentation contours.
- No broken or aliased pixels on the skin.
- No visible mask edges.
- The final image must look like a single coherent photograph, not a composite.

Return one realistic final image only.`;

// ──────────────────────────────────────────────────────────────────────────
//  Watch — ultra-strict variant. Used when the placement is automatic and
//  the product is the most identity-sensitive accessory (dial, bezel,
//  colored accents, bracelet links).
// ──────────────────────────────────────────────────────────────────────────

export function getWatchTryOnPrompt(): string {
  return `You are editing a realistic e-commerce watch try-on image.

The first image is the main source of truth. It already contains the customer photo with the watch placed in the intended wrist position.
The product reference image shows the exact watch that must be preserved.

Your task is not to generate or redesign a watch.
Your task is only to make the already placed watch look naturally worn on the wrist.

Strict rules:
- Show one watch only.
- Do not duplicate the watch.
- Do not add a second watch.
- Do not create a background watch.
- Do not replace the watch with another watch.
- Do not redesign the watch.
- Do not simplify the watch.
- Do not recolor the watch.
- Preserve the exact watch identity from the reference image.

Preserve exactly:
- case shape
- bezel
- dial layout
- subdials
- logo placement
- date window
- hands
- color accents
- bracelet links
- material
- overall style

Placement and realism rules:
- Keep the watch centered on the wrist.
- Align the watch with the wrist and forearm axis.
- Follow the natural angle of the arm.
- Apply realistic rotation so the watch matches the wrist orientation.
- The watch must not appear flat or pasted.
- The bracelet should visually follow the wrist direction and wrap naturally.
- Improve perspective realism, realistic contact, shadows, and slight skin occlusion where appropriate.

Customer preservation rules:
- Preserve the hand, fingers, nails, skin texture, arm hair, wrist shape, and background outside the masked area.
- Do not change anatomy.
- Do not modify hand shape.
- Do not modify finger length or finger position.
- Do not repaint or regenerate the customer image.

Mask rule:
- The mask is only a technical editing guide.
- It must never appear in the final image.
- No white outlines.
- No black outlines.
- No visible segmentation marks.
- No broken pixels on the skin.

Return one final realistic image only.`;
}

// ──────────────────────────────────────────────────────────────────────────
//  No-mask fallback — experimental only. Used when the auto-mask
//  pipeline could not produce a usable mask (rare edge case) AND the
//  operator explicitly opted into free generation. Less reliable.
// ──────────────────────────────────────────────────────────────────────────

export function getNoMaskFallbackPrompt(): string {
  return `Create a realistic virtual try-on using the customer photo and the product reference image.

Place the exact product from the reference image onto the appropriate body area of the customer. Preserve the product identity as strictly as possible.

Do not replace, redesign, recolor or simplify the product. Preserve the exact color, material, shape, logo, decorations, structure and visible details.

Preserve the customer photo as much as possible. Do not alter the customer's anatomy, face, hand, skin texture, nails, hair, clothing or background.

For a watch, place the exact watch on the wrist with realistic scale, perspective, bracelet wrapping, shadows and contact. Do not create another watch.

Return a realistic photo-quality result.`;
}

// ──────────────────────────────────────────────────────────────────────────
//  Public API
// ──────────────────────────────────────────────────────────────────────────

function pickAccessoryLockLead(o: OpenAITryOnPromptOptions): string {
  switch (o.category) {
    case "watch":
      return watchLockLead();
    case "glasses":
      return glassesLockLead();
    case "headwear":
      return headwearLockLead();
    case "hand-jewelry":
      if (o.productSubtype === "ring") return ringLockLead(o);
      if (o.productSubtype === "bracelet") return braceletLockLead();
      return genericHandJewelryLockLead();
    case "clothes":
      // Clothes do not use the lock pipeline; this branch is unreachable
      // in practice but kept for exhaustiveness.
      return ACCESSORY_LOCK_GENERIC;
  }
}

function pickPlacementLead(o: OpenAITryOnPromptOptions): string {
  switch (o.category) {
    case "watch":
      return watchLead();
    case "glasses":
      return glassesLead();
    case "headwear":
      return headwearLead();
    case "hand-jewelry":
      if (o.productSubtype === "ring") return ringLead(o);
      if (o.productSubtype === "bracelet") return braceletLead();
      return genericHandJewelryLead();
    case "clothes":
      return clothesLead();
  }
}

export function buildOpenAITryOnPrompt(o: OpenAITryOnPromptOptions): string {
  const isAccessory = o.category !== "clothes";
  const useLock = Boolean(o.productLocked) && isAccessory;
  const useAutoMasked = Boolean(o.autoMaskedAccessory) && isAccessory;

  // Highest priority: a deterministic composite + auto-mask was sent.
  // Use the ultra-strict integration-only prompts (watch gets the
  // identity-locked variant, others get the auto-masked accessory
  // template). These never mention placement because the placement
  // is already baked into the composite.
  if (useAutoMasked) {
    let prompt =
      o.category === "watch"
        ? getWatchTryOnPrompt()
        : AUTO_MASKED_ACCESSORY_PROMPT;
    if (o.notes && o.notes.trim()) {
      prompt += `\n\nAdditional context: ${o.notes.trim()}`;
    }
    return prompt;
  }

  // Mid priority: product-lock pipeline is engaged but the auto-mask
  // flag wasn't explicitly set (e.g. external caller). Use the
  // legacy per-category lock leads + the product-lock footer.
  if (useLock) {
    const lead = pickAccessoryLockLead(o);
    const footer = productLockFooter();
    let prompt = `${lead}\n\n${footer}`;
    if (o.notes && o.notes.trim()) {
      prompt += `\n\nAdditional context: ${o.notes.trim()}`;
    }
    prompt +=
      "\n\nReturn a realistic e-commerce virtual try-on preview. Do " +
      "not redraw the product itself — only refine local lighting and " +
      "shadows.";
    return prompt;
  }

  // Free-generation / no-mask path. Reserved for clothes (uses
  // category lead + standard preservation footer) and the
  // experimental accessory fallback (when the auto-mask failed).
  if (isAccessory) {
    // Accessory without composite/mask: use the conservative no-mask
    // fallback prompt rather than the looser placement lead.
    let prompt = getNoMaskFallbackPrompt();
    if (o.notes && o.notes.trim()) {
      prompt += `\n\nAdditional context: ${o.notes.trim()}`;
    }
    return prompt;
  }

  const lead = pickPlacementLead(o);
  const footer = preservationFooter({ maskUsed: o.maskUsed });
  let prompt = `${lead}\n\n${footer}`;
  if (o.notes && o.notes.trim()) {
    prompt += `\n\nAdditional context: ${o.notes.trim()}`;
  }
  prompt +=
    "\n\nReturn a realistic e-commerce virtual try-on preview. Do " +
    "not include any product background. Do not paste the product " +
    "as a flat sticker.";
  return prompt;
}

/**
 * Per-category mask flags. Each defaults to true unless explicitly set
 * to "false" via env. Allows operators to disable masked editing for a
 * specific category without rebuilding.
 */
export function isMaskedEditEnabledFor(category: CategoryId): boolean {
  const globalFlag = process.env.OPENAI_USE_MASKED_EDIT?.trim().toLowerCase();
  if (globalFlag === "false") return false;

  const perCategoryRaw = (() => {
    switch (category) {
      case "watch":
        return process.env.WATCH_USE_MASKED_EDIT;
      case "glasses":
        return process.env.GLASSES_USE_MASKED_EDIT;
      case "headwear":
        return process.env.HEADWEAR_USE_MASKED_EDIT;
      case "hand-jewelry":
        return process.env.HAND_JEWELRY_USE_MASKED_EDIT;
      case "clothes":
        return process.env.CLOTHES_USE_MASKED_EDIT;
    }
  })();
  return (perCategoryRaw?.trim().toLowerCase() ?? "true") !== "false";
}
