export type CategoryId =
  | "headwear"
  | "watch"
  | "hand-jewelry"
  | "clothes"
  | "glasses";

export type ProductInputMode = "single" | "multi";

export type AnimationType =
  | "hatmaker"
  | "watchmaker"
  | "jeweler"
  | "tailor"
  | "optician";

export type IconName =
  | "hat"
  | "watch"
  | "gem"
  | "shirt"
  | "glasses";

/** Visual scene played in the animated photo guide for a single step. */
export type PhotoSceneId =
  | "frame"      // Frame the body part / set distance
  | "angle"      // Hold the right angle
  | "lighting"   // Soft, even, natural light
  | "background" // Plain neutral background
  | "remove"     // Remove existing accessory (e.g. glasses)
  | "stable"     // Stay still, no motion blur
  | "pose"       // Stand straight / posture
  | "outfit";    // Wear something fitted underneath

export interface PhotoStep {
  /** Short, action-oriented title shown as the step header. */
  title: string;
  /** One-sentence elaboration shown under the title. */
  hint: string;
  /** Which scene to render in the central animated illustration. */
  scene: PhotoSceneId;
}

export interface Category {
  id: CategoryId;
  label: string;
  shortDescription: string;
  bodyTarget: string;
  /** Legacy plain instructions (kept for backward compatibility). */
  photoInstructions: string[];
  /** Step-by-step animated guide. */
  photoSteps: PhotoStep[];
  /**
   * One clear, action-oriented sentence telling the customer exactly
   * what to photograph. Shown in step 1 in place of the legacy
   * multi-step animated guide.
   */
  photoSingleInstruction: string;
  productInputMode: ProductInputMode;
  loadingTitle: string;
  loadingDescription: string;
  animationType: AnimationType;
  iconName: IconName;
}

export type WizardStep = 1 | 2 | 3;

export type TryOnStatus =
  | "idle"
  | "validating"
  | "loading"
  | "revealing"
  | "done"
  | "error";

export type ProductSource =
  | "user"
  | "shopify"
  | "opengraph"
  | "jsonld"
  | "direct-image"
  | "unknown";

export interface ProductItem {
  id: string;
  type: "url" | "image";
  value: string;
  file?: File;
  previewUrl?: string;
  source?: ProductSource;
  title?: string;
  /** Transparent PNG cutout URL, produced by /api/product/cutout. */
  cutoutUrl?: string;
  /** Whether the cutout is currently being computed. */
  cutoutPending?: boolean;
  /** Last cutout error message, if any. */
  cutoutError?: string;
}

export type FingerId = "index" | "middle" | "ring" | "pinky";
export type HandJewelryType = "ring" | "bracelet";

export interface TryOnRequest {
  category: CategoryId;
  userImage: File;
  productImages: File[];
  productUrls: string[];
  /**
   * Optional, server-resolved transparent product cutouts (PNG with
   * alpha). The /api/try-on route downloads cutout URLs so providers
   * can use them as high-fidelity references without leaking URLs.
   */
  productCutoutBuffers?: Buffer[];
  notes?: string;
  merchantId?: string;
  /** Optional deterministic preview produced client-side. */
  previewImage?: File;
  /** Hand-jewelry subtype (ring | bracelet). */
  handJewelryType?: HandJewelryType;
  /** Target finger for rings. */
  ringFinger?: FingerId;
  /** Render mode requested by the client. */
  renderModeRequest?: "fast" | "premium" | "auto";
  /**
   * Inpainting refinement pack. When both fields are provided, the
   * service routes to a mask-aware model:
   *  - openai → gpt-image-1 image edit with alpha mask.
   *  - fal    → FLUX Fill / FLUX LoRA Inpainting.
   * Unmasked pixels are preserved exactly — protecting product details
   * and hand/face anatomy.
   */
  inpaintComposite?: File;
  inpaintMask?: File;
}

export interface TryOnResponseDebug {
  imageCount: number;
  productImageCount: number;
  productWasCutout?: boolean;
  productImageSource?: "transparent-upload" | "cutout" | "original";
  productHasAlpha?: boolean;
  productMimeType?: string;
  /** True when the request was handled by the OpenAI provider. */
  usedOpenAI?: boolean;
  /** True when the request was handled by a fal.ai model. */
  usedFal?: boolean;
  /**
   * True when the API returned a locally rendered image (fast-overlay /
   * canvas) as the *final* result. In API-only mode this must always be
   * false.
   */
  usedLocalRenderer?: boolean;
  /** Whether an OpenAI alpha mask was attached to the edit call. */
  maskUsed?: boolean;
  /** Whether the product-lock pipeline successfully re-stamped the product. */
  productLocked?: boolean;
  /** True when both composite + mask were generated by the app (no client mask). */
  autoMaskGenerated?: boolean;
  /** True when a composite was used as the base image sent to OpenAI. */
  compositeUsed?: boolean;
  /** True when the eligibility criteria for the product-lock pipeline were met. */
  productLockCandidate?: boolean;
  /** True when the product-lock re-stamp was actually applied. */
  productLockApplied?: boolean;
  /** True when the deterministic composite was returned as the final result. */
  fallbackUsed?: boolean;
  /** Width × height (px) of the canonical input image after resizing. */
  inputDimensions?: { width: number; height: number };
  /** Ratio of bright pixels in the mask sent to OpenAI (0..1). */
  maskCoverage?: number;
  /** True when the product reference had a usable alpha channel. */
  productAlphaDetected?: boolean;
  /** True when the post-generation product fidelity check flagged the result. */
  qualityCheckFailed?: boolean;
}

/** Lightweight server-side fidelity checks computed after generation. */
export interface QualityChecks {
  /** 0..1 score, higher is more preserved (outside-mask area). */
  outsideMaskChangeScore: number;
  /** True when the score >= preservation threshold (default 0.92). */
  outsideMaskPreserved: boolean;
  /** True when the product reference is below the resolution threshold. */
  productFidelityWarning: boolean;
  /** Aggregate flag: anything that should make the operator double-check. */
  customerPreservationWarning: boolean;
  /**
   * True when the original product PNG was re-stamped on top of the AI
   * result (product-lock pipeline). Always false for clothes.
   */
  productLocked?: boolean;
  /** How product fidelity was enforced for this generation. */
  productFidelityMode?:
    | "ai-only"
    | "locked-overlay-after-ai"
    | "locked-overlay-skipped";
  /**
   * Ratio of pixels considered "product silhouette" when running the
   * lock pipeline. Useful for debugging. 0..1.
   */
  productSilhouetteRatio?: number;
}

export type RenderMode =
  | "fast-overlay"
  | "premium-ai"
  | "specialized-vton"
  | "api-image-edit"
  /** OpenAI image edit + product-lock re-stamp on top (accessories). */
  | "api-image-edit-product-lock"
  | "mock";

export type QualityStatus =
  | "passed"
  | "fallback-preview"
  | "needs-better-photo"
  | "needs-manual-adjustment"
  | "alpha-lost"
  | "failed"
  // ── Fallback variants ────────────────────────────────────────────
  // All `fallback_*` codes mean: the AI result was not validated, the
  // route shipped the deterministic composite instead. The customer
  // ALWAYS receives `ok=true` + `resultUrl`. The status is exposed for
  // analytics / QA dashboards. The frontend collapses every variant
  // into a single soft note via `pickCustomerFacingNote`.
  | "fallback_customer_preservation"
  | "fallback_product_fidelity"
  | "fallback_mask_too_small"
  | "fallback_mask_too_large"
  | "fallback_mask_validation"
  | "fallback_mask_dimensions";

export interface TryOnWarning {
  code: string;
  message: string;
}

export interface WatchPlacementResponse {
  x: number;
  y: number;
  scale: number;
  rotation: number;
  curvature: number;
  confidence: number;
}

export interface TryOnResponse {
  resultUrl: string;
  /** Optional client-side deterministic preview, if any. */
  previewUrl?: string;
  generatedAt: number;
  mock?: boolean;
  provider?: string;
  model?: string;
  category?: CategoryId;
  /** Server-side generation duration in milliseconds. */
  durationMs?: number;
  /** Debug counts. Only safe scalars — never URLs or PII. */
  debug?: TryOnResponseDebug;
  renderMode?: RenderMode;
  qualityStatus?: QualityStatus;
  warnings?: TryOnWarning[];
  /** Watch-only: placement actually used for the deterministic overlay. */
  placement?: WatchPlacementResponse;
  /** Watch-only: alpha edge-quality score in [0..1]. */
  edgeQuality?: number;
  /** Server-computed fidelity checks (OpenAI path). */
  qualityChecks?: QualityChecks;
  /**
   * Mirror of the strict-fidelity guarantees enforced by the OpenAI
   * prompt. Always true for the OpenAI path; surfaces in the API
   * response so dashboards / tests can assert on them.
   */
  preserveCustomerStrict?: boolean;
  preserveProductStrict?: boolean;
  /**
   * Top-level mirror of `qualityChecks.productLocked` for callers that
   * just want to know "did the original product PNG win?". Mirrors the
   * spec's `productLocked` field on the API response.
   */
  productLocked?: boolean;
}

export interface ProductResolveResult {
  title?: string;
  imageUrl?: string;
  source: ProductSource;
}

export interface TryOnResultMeta {
  provider?: string;
  model?: string;
  mock?: boolean;
  renderMode?: RenderMode;
  qualityStatus?: QualityStatus;
  warnings?: TryOnWarning[];
  /** Mirror of debug.maskUsed for UI consumption. */
  maskUsed?: boolean;
  /** Mirror of debug.usedLocalRenderer for UI consumption. */
  usedLocalRenderer?: boolean;
  /** Quality checks computed server-side (OpenAI path). */
  qualityChecks?: QualityChecks;
  /** Top-level mirror of qualityChecks.productLocked for UI consumption. */
  productLocked?: boolean;
  /** Mirror of debug.fallbackUsed for UI consumption. */
  fallbackUsed?: boolean;
  /** Mirror of debug.autoMaskGenerated for UI consumption. */
  autoMaskGenerated?: boolean;
}

export interface TryOnState {
  step: WizardStep;
  userImage: File | null;
  userImagePreview: string | null;
  products: ProductItem[];
  notes: string;
  status: TryOnStatus;
  error: string | null;
  resultUrl: string | null;
  resultMeta: TryOnResultMeta | null;
}

export type TryOnAction =
  | { type: "SET_STEP"; step: WizardStep }
  | { type: "SET_USER_IMAGE"; file: File; previewUrl: string }
  | { type: "CLEAR_USER_IMAGE" }
  | { type: "ADD_PRODUCT"; product: ProductItem }
  | {
      type: "UPDATE_PRODUCT";
      id: string;
      patch: Partial<Omit<ProductItem, "id">>;
    }
  | { type: "REMOVE_PRODUCT"; id: string }
  | { type: "CLEAR_PRODUCTS" }
  | { type: "SET_NOTES"; notes: string }
  | { type: "SET_STATUS"; status: TryOnStatus }
  | { type: "SET_ERROR"; error: string | null }
  | { type: "SET_RESULT"; resultUrl: string; meta?: TryOnResultMeta }
  | { type: "RESET_ARTICLES" }
  | { type: "RESET_TRY_AGAIN" }
  /**
   * Like RESET_ARTICLES but PRESERVES the user photo. Used when the
   * customer clicks "Try another model" in the assistant bubble — we
   * want them to land back on the product step without having to
   * re-upload their selfie.
   */
  | { type: "RESET_PRODUCT_KEEP_PHOTO" }
  | { type: "RESET_ALL" };

// ──────────────────────────────────────────────────────────────────
//  Assistant bubble (shopping-assistant overlay around the try-on)
// ──────────────────────────────────────────────────────────────────

export type TryOnAssistantStatus =
  | "idle"
  | "preparing"
  | "analyzing_photo"
  | "preparing_product"
  | "placing_product"
  | "generating"
  | "quality_check"
  | "ready"
  | "fallback_ready"
  | "error";

export interface TryOnAssistantMessage {
  id: string;
  role: "assistant" | "system" | "user";
  text: string;
  createdAt: number;
  kind?: "info" | "progress" | "success" | "warning" | "error" | "opinion";
}

/**
 * State of a single try-on attempt. An entry stays in the history
 * feed in every state — the customer can scroll up and see in-flight
 * simulations, finished ones and even interrupted ones, each with
 * the right UI inside its card.
 */
export type TryOnEntryStatus = "pending" | "ready" | "error" | "interrupted";

/**
 * A single try-on attempt. The bubble keeps an array of these so the
 * customer can scroll up and see every article they tried during the
 * visit — each card has its own share / add-to-cart / agrandir
 * controls, and renders the right UI for its current `status`.
 */
export interface TryOnHistoryEntry {
  id: string;
  jobId: string;
  category: CategoryId;
  productTitle?: string;
  productUrl?: string;
  productImage?: string;
  /** Lifecycle status of this attempt. */
  status: TryOnEntryStatus;
  /** Progress 0..100 — populated while pending, frozen at the last value otherwise. */
  progress: number;
  /** Optional pipeline sub-stage, used by the simulation panel for the label. */
  stageStatus?: TryOnAssistantStatus;
  /** Populated when status === "ready". */
  resultUrl?: string;
  shareUrl?: string;
  /** Customer-facing one-liner, only when status === "ready". */
  opinion?: string;
  /** When the renderer fell back to a deterministic composite. */
  fallbackUsed?: boolean;
  /** Customer-facing error message for status === "error" / "interrupted". */
  errorMessage?: string;
  cartStatus: "idle" | "adding" | "added" | "error";
  createdAt: number;
}

export interface TryOnAssistantState {
  active: boolean;
  minimized: boolean;
  status: TryOnAssistantStatus;
  progress: number;
  messages: TryOnAssistantMessage[];
  /**
   * @deprecated The latest entry lives in `history[history.length-1]`.
   * Kept here for backward compatibility with older persisted state
   * and minimised-pill behaviour.
   */
  resultUrl?: string;
  productTitle?: string;
  productUrl?: string;
  productImage?: string;
  category?: CategoryId;
  canAddToCart?: boolean;
  /** Cart status of the CURRENT in-flight job (per-card lives on each entry). */
  cartStatus?: "idle" | "adding" | "added" | "error";
  shareUrl?: string;
  fallbackUsed?: boolean;
  /** Stable identifier for the running job — emitted in postMessages. */
  jobId?: string;
  /**
   * Chronological list of completed try-ons. Newest at the END so
   * the bubble can render them in chat-style order with the latest
   * pinned at the bottom and older ones revealed by scrolling up.
   */
  history: TryOnHistoryEntry[];
}

export type SharePlatform =
  | "native"
  | "whatsapp"
  | "viber"
  | "messenger"
  | "instagram"
  | "email"
  | "copy";
